### ISSUE TITLE
Cant Install ZIP Repo

### ISSUE THREAD

**Issue by develarts** [streamxstream/xStreamRepo#12]
Hallo, ich kann das Repo nicht installieren. Bei mir kommt die Fehlermeldung " Invalid Structure " 
Die ZIP ist 1:1 gedownloadet und über FTP übertragen. 
Habe mehrere Versionen von KODi ausprobieren (19/20/21).

**Comment by develarts** [comment]
Hat jetzt geklappt über Web Repo Install. Wahrscheinlich muss man die ZIP vorher anpassen, wäre nett wenn man das zur Info mit dabei schreibt, weiß jetzt nicht was mit der ZIP falsch war

**Comment by DWH-WFC** [comment]
Nein wird nicht angepasst vorher. Wenn du die ZIp sauber geladen hast kannst du sie manuell sowie auch über das Web installieren. Funktioniert beides einwandfrei. Vermutlich ist bei deiner FTP Übertragung was schief gelaufen
