### ISSUE TITLE
Hijacking Metahandler

### ISSUE THREAD

**Issue by Eldorados** [streamxstream/xStreamRepo#2]
If you wished to have changes done to metahandler I would have gladly accepted any pull requests

I'm not too happy seeing my addon that I created and maintained for years being hijacked and my name stripped from the code

With the upcoming Kodi v19 they will be enforcing which repo's addons come from, looks like I will need to submit an updated version to protect from things like this

**Comment by anis3** [comment]
Hello Eldorados

you are right i made a mistake and want to
gladly correct it.

I didn't think about it when I got her name out of the
Removed code can understand that they are not happy there
i have corrected the mistake and hope that you can forgive me

I checked your code is not compatible with the code
where i use the code is probably based on an old version
from you i would like to continue to use the code if you agree
and based on your current code i would like to use your add-on in the future if you agree

if you are ready to work together i would love to hear from you
help to write your code python3 compatible
and to submit it to you in the future

The best way to reach me is https://gitter.im/anis3

LG Anis3

**Comment by anis3** [comment]
Hello Eldorados

You are right, I made a mistake and corrected it
I didn't think about it when I removed your name from the code
hope you forgive me

I checked that your current code is compatible
with the code base where I am using
Unfortunately not

I want to keep using the code in the future
When you're ready, I'll be happy to help you write your Python3 compatible code

I want to switch to your codebase in the future
if it is Python3 compatible

Please write to me if you agree

you can reach me the best https://gitter.im/anis3

LG Anis3

**Comment by anis3** [comment]
Hello Eldorados after your nice message
and that you no react
have i Metahandler
remove from my project

I wrote to you about gitter.im
that I will leave the metahandler here until the beginning of 2021 and then delete it

i just wanted to keep the project alive
It was not intended to remove your name

I wrote something of my own for my project
and am very happy about it 
only about 1/10 code & much faster
compared to metahandler

I'm no longer interested in Metahandlers

I find it sad that you
metahandler for years
let die

You can my changes take
I have no problem with that
is yes open source
works without problems with Kodi 18/19

from my side it is called but

R.I.P. Metahandler
