### ISSUE TITLE
Anicloud and Serienstream issue 

### ISSUE THREAD

**Issue by Dr3amX** [streamxstream/xStreamRepo#7]
It seems that xstream has its issues with playing content from these 2 and other providers ,because there using a captcha to solve befor watching a stream . when i open a movie or eposide directly on the page it let me solve a captcha .. but in kodi when i try to watch the same stuff it tells me that it failed . so are there any solutions to this ?

**Comment by Heptamer** [comment]
Streams on both sites are fully working. Without knowing which streams and hosters are not working as intended, neither having any information about the KODi, xstream and resolveurl version we wont bei able to validate the reported error.

Btw: German is possible as well 😉

**Comment by Dr3amX** [comment]
oke dann auf deutsch weiter . ich versuche auf anicloud und auf serienstream tokyo ghoul abzuspielen . aber wen ich auf eine folge klicke kommt ganz kurz start opening. aber das fenster geht ganz schnell wieder weg und es startet keine folge . manchmal kommt auch die meldung one or more items has failed to play . oder oben rechts in der ecke "stream nicht mehr verfügbar oder fehlerhafter link. aber wenn ich die seite besuche funktioniert alles operfekt aslso muss es an meinem kodi/xstream liegen ?

**Comment by Heptamer** [comment]
Hab gerade Mal auf Serienstream danach gesucht und abgespielt. Der Hoster VOE hat die Episoden nicht, unter Streamtape läuft's.

Ich vermute mal du hast in den Xstream Einstellungen die Hoster-Auswahl auf Auto, und du prüfst aber nicht ab ob die streams überhaupt da sind. Genau dann passiert das was du gerade beschreibst.

Daher, meine Empfehlung: Hoster-Auswahl auf Dialog stellen und wenn dann einer nicht funktioniert einfach einen anderen nehmen.

**Comment by Dr3amX** [comment]
Habe in den einstellungen geschaut stand auf Dialog ! also daran kann es nicht liegen ?

**Comment by Dr3amX** [comment]
bekomme bei streamtape aber auch die meldung das der link nicht mehr verfügbar sei !

**Comment by Heptamer** [comment]
Beantworte bitte erst noch mal meine Frage zu den Versionen von weiter oben. Wäre auch hilfreich zu wissen was genau von welcher Seite du ausprobiert hast, sonst kann man das nicht nachvollziehen.

**Comment by Dr3amX** [comment]
da habe ich keine ahnung wo das steht bin auf dem gebiet nicht so bewandert !

**Comment by Heptamer** [comment]
Und den Rest kannst du auch nicht beantworten? Bitte immer alles lesen...

**Comment by Dr3amX** [comment]
wenn es keine umstände macht bitte einmal kurz alles schreiben was du wissen möchtest .. ich versuche dann die informationen zu finden danke :)

**Comment by Heptamer** [comment]
Kein Problem:
Welcher Film/welche Serie/Folge von welcher Seite geht bei Dir nicht, und mit welchem Hoster (VOE, Streamtape usw) hast Du das probiert?
Die Versionsnummer von xstream und Kodi wären dann noch hilfreich. :)

**Comment by Dr3amX** [comment]
wenn ich das Richtig gelesen habe ist es Kodi Version 19.4 (19.4.0) und xtream ist 3.5.35 falls das das richtige ist :)

Das Problem was bei ALLEN serien bei mir auftritt ist folgendes : https://youtu.be/NdPNmTQ2iGI

habe da ein kurzes video gemacht ich glaube das erklärt es . zur info alles folgen die ich im video anklicke funktionieren auf  aniworld bei alles hostern ohne probleme !

**Comment by Heptamer** [comment]
Ich hab jetzt mal die Beispiele aus deinem Video nachgestellt, bei mir laufen alle streams problemlos. 

Was passiert denn wenn du über xstream die Serie aufrufst und nicht über die Favoriten? Evtl sind das alte Einträge die nicht mehr passen.

Bitte schau auch mal nach der Versionsnummer des resolveurl, vielleicht liegt da das Problem. Die findest du am einfachsten wenn du in die Addons gehst, da auf xstream - Informationen und dort auf Abhängigkeiten. Dann nach dem resolveurl (nicht repo) suchen, draufklicken und dann die angezeigte Versionsnummer notieren. Sollte mindestens 5.1.73 sein.

**Comment by Dr3amX** [comment]
ich denke das problem liegt hier bei der resolve url da habe ich 5.1.69 . wenn ich aber auch versionen drücke bzw auf update ist das die neuste version die ich bekomme ? wo ist da meine möglichkeit das zu updaten ? und das eigene nightly update wie waären da die schritte das zu installieren ? 

schonmal danke für die hilfe :)

**Comment by MartinX3** [comment]
In den Einstellungen des Addons gibt's den Schalter zum aktivieren des Nightlies.

Ich weiß nicht, ob er funktioniert, da er bei mir weiterhin nur die Version von diesem Repo findet:
https://github.com/streamxstream/plugin.video.xstream/releases/tag/3.5.35

**Comment by Dr3amX** [comment]
Wenn ich um Nightly Update auf Update resolveurl gehe sagt ewer mir update erfolgreich aber ich habe trotzdem nur die version 5.1.69 und scheine auch keine höhere zu bekommen

**Comment by Heptamer** [comment]
Dann installiere dir doch aus dem xstream repo noch das resolveurl repo und mach dann darüber dass Update für den resolveurl.

**Comment by Dr3amX** [comment]
wenn ich versuche das aktuelle xstream repo zu installieren steht da failes due to an invalid structure
