### ISSUE TITLE
Das selbe problem!

### ISSUE THREAD

**Issue by Dr3amX** [streamxstream/xStreamRepo#8]
Weswegen wird hier was Geschlossen mein Problem wurde nicht behoben .Es wäre schön wenn ich hilfe bekämen würde ? Bitte !

**Comment by Heptamer** [comment]
Weil von meiner Seite aus alles funktioniert. Und wenn du nicht mal ein konkretes Beispiel nennen kannst wo etwas nicht klappt bleibt das auch so.
